@base-url = http://localhost:5000

POST {{base-url}}/users/register
Content-Type: application/json

{
  "phoneNumber": "03356423333",
  "password": "password",
  "fullName": "Hadeed Ahmad",
  "address": "LUMS",
  "gender": 1
}

> {% if (response.body.token) client.global.set("jwt", response.body.token); %}

###

POST {{base-url}}/users/login
Content-Type: application/json

{
  "phonenumber": "03356423333",
  "password": "password"
}

> {% if (response.body.token) client.global.set("jwt", response.body.token); %}

###

POST {{base-url}}/verify/start-sms
Authorization: Bearer {{jwt}}

###

POST {{base-url}}/verify/end-sms
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "code": "413961"
}

> {% if (response.body.token) client.global.set("jwt", response.body.token); %}
