###
POST http://localhost:5000/users/register
Content-Type: application/json

{
  "username": "hadeedahasdf",
  "password": "password",
  "phonenumber": "03356423333"
}

###
POST http://localhost:5000/users/login
Content-Type: application/json

{
  "username": "hadeed",
  "password": "password"
}

###
POST http://localhost:5000/api/user/send-verification-sms

###
POST http://localhost:5000/api/user/verify-sms?code=988455
Content-Type: application/json
