services:
  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
  
  seq:
    image: datalust/seq:latest
    container_name: seq-server
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5341:80"